name: SAST Workflow

on:
  push:
    branches: [ master, develop, release/* ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '49 20 * * 0' #mudar horario

jobs:
  tfsec:
    name: TFSec
    uses: getzoop/gha-workflows/.github/workflows/tfsec.yml@v5
  codeql:
    name: CodeQL
    uses: getzoop/gha-workflows/.github/workflows/codeql.yml@v5
    with:
      language: python
