name: SAST Workflow

on:
  push:
    branches: [ master, main, develop, release/* ]
  pull_request:
    branches: [ master, main ]

jobs:
  tfsec:
    name: TFSec
    uses: getzoop/gha-workflows/.github/workflows/tfsec.yml@v5
